/** @type {import('tailwindcss').Config} */
module.exports = {
    blocklist: ["overline"],
    darkMode: ["class"],
    content: ["./src/**/*.{js,jsx,ts,tsx}", "./index.html"],
    theme: {
        extend: {
            fontFamily: {
                display: ["Outfit", "Plus Jakarta Sans", "sans-serif"],
                sans: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
                mono: ["JetBrains Mono", "monospace"],
            },
            borderRadius: {
                lg: "var(--radius)",
                md: "calc(var(--radius) - 4px)",
                sm: "calc(var(--radius) - 8px)",
                "2xl": "1.25rem",
                "3xl": "1.75rem",
            },
            colors: {
                background: "var(--background)",
                "background-secondary": "var(--background-secondary)",
                "background-tertiary": "var(--background-tertiary)",
                foreground: "var(--foreground)",
                card: { DEFAULT: "var(--card)", foreground: "var(--card-foreground)" },
                popover: { DEFAULT: "var(--popover)", foreground: "var(--popover-foreground)" },
                primary: { DEFAULT: "var(--primary)", foreground: "var(--primary-foreground)" },
                secondary: { DEFAULT: "var(--secondary)", foreground: "var(--secondary-foreground)" },
                muted: { DEFAULT: "var(--muted)", foreground: "var(--muted-foreground)" },
                accent: { DEFAULT: "var(--accent)", foreground: "var(--accent-foreground)" },
                destructive: { DEFAULT: "var(--destructive)", foreground: "var(--destructive-foreground)" },
                border: "var(--border)",
                input: "var(--input)",
                ring: "var(--ring)",
                surface: { hover: "var(--surface-hover)" },
                success: "var(--status-success)",
                warning: "var(--status-warning)",
                error: "var(--status-error)",
                plum: "#3A202F",
                burgundy: "#5A3045",
                rose: "#B56C82",
                "soft-rose": "#E5B8C2",
                warm: "#F8F3F5",
                chart: {
                    1: "var(--chart-1)",
                    2: "var(--chart-2)",
                    3: "var(--chart-3)",
                    4: "var(--chart-4)",
                    5: "var(--chart-5)",
                },
            },
            keyframes: {
                "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
                "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
            },
            animation: {
                "accordion-down": "accordion-down 0.2s ease-out",
                "accordion-up": "accordion-up 0.2s ease-out",
            },
        },
    },
    plugins: [require("tailwindcss-animate")],
};
